# Generated by Django 6.1.1 on 2026-09-20 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLARule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('metric', models.CharField(choices=[('packet_loss_pct', 'Packet loss (%)'), ('latency_ms', 'Latency (ms)'), ('jitter_ms', 'Jitter (ms)'), ('availability_pct', 'Availability (%)'), ('outage_duration_s', 'Outage duration (s)'), ('throughput_mbps', 'Throughput (Mbps)'), ('dns_resolution_ms', 'DNS resolution time (ms)')], max_length=30)),
                ('operator', models.CharField(choices=[('gt', '>'), ('gte', '>='), ('lt', '<'), ('lte', '<='), ('eq', '==')], max_length=5)),
                ('threshold', models.FloatField()),
                ('unit', models.CharField(blank=True, default='', max_length=20)),
                ('min_duration_seconds', models.PositiveIntegerField(default=0, help_text='The breach must have lasted at least this long to count (0 = any duration)')),
                ('measurement_window_seconds', models.PositiveIntegerField(help_text='Rolling window size for periodic evaluation, e.g. 2592000 for a 30-day window')),
                ('protocol', models.CharField(blank=True, default='', max_length=10)),
                ('destination_filter', models.CharField(blank=True, default='', help_text='Target name/address substring; blank = all targets', max_length=255)),
                ('time_period_filter', models.CharField(blank=True, default='', help_text='e.g. "business_hours"; blank = all times', max_length=100)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=10)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SLAEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('observed_value', models.FloatField(blank=True, null=True)),
                ('threshold_value', models.FloatField()),
                ('status', models.CharField(choices=[('satisfied', 'Satisfied'), ('breached', 'Breached'), ('insufficient_data', 'Insufficient data')], max_length=20)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sla_evaluations', to='incidents.incident')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='sla.slarule')),
            ],
            options={
                'ordering': ['-window_end'],
            },
        ),
    ]
