# Generated by Django 6.1.1 on 2026-09-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('icmp', 'ICMP latency/loss'), ('dns', 'DNS resolution'), ('http', 'HTTP/HTTPS'), ('tcp', 'TCP connect'), ('route', 'Route trace'), ('mtu', 'MTU/PMTUD'), ('throughput', 'Throughput'), ('bufferbloat', 'Bufferbloat'), ('interface', 'Interface metrics')], max_length=20, unique=True)),
                ('raw_retention_days', models.PositiveIntegerField(blank=True, help_text='Blank = keep raw data indefinitely', null=True)),
                ('aggregate_retention_days', models.PositiveIntegerField(blank=True, help_text='Blank = keep aggregates indefinitely', null=True)),
            ],
            options={
                'ordering': ['data_type'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('icmp', 'ICMP latency/loss'), ('dns', 'DNS resolution'), ('http', 'HTTP/HTTPS'), ('tcp', 'TCP connect'), ('route', 'Route trace'), ('mtu', 'MTU/PMTUD'), ('throughput', 'Throughput'), ('bufferbloat', 'Bufferbloat'), ('interface', 'Interface metrics')], max_length=20, unique=True)),
                ('interval_seconds', models.PositiveIntegerField()),
                ('enabled', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['task_type'],
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('gateway', 'Default gateway'), ('isp_hop', 'ISP first hop'), ('internet', 'Internet endpoint'), ('dns', 'DNS resolver'), ('http', 'HTTP(S) endpoint'), ('custom', 'Custom')], max_length=20)),
                ('address', models.CharField(help_text='Hostname or IP address', max_length=255)),
                ('address_family', models.CharField(choices=[('ipv4', 'IPv4'), ('ipv6', 'IPv6')], default='ipv4', max_length=4)),
                ('protocol', models.CharField(choices=[('icmp', 'ICMP'), ('tcp', 'TCP'), ('udp', 'UDP'), ('http', 'HTTP'), ('https', 'HTTPS'), ('dns', 'DNS')], max_length=10)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
