# Generated by Django 6.1.1 on 2026-09-20 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnDemandTestRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('icmp', 'ICMP latency/loss'), ('dns', 'DNS resolution'), ('http', 'HTTP/HTTPS'), ('tcp', 'TCP connect'), ('route', 'Route trace'), ('mtu', 'MTU/PMTUD'), ('throughput', 'Throughput'), ('bufferbloat', 'Bufferbloat'), ('interface', 'Interface metrics')], max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddField(
            model_name='target',
            name='port',
            field=models.PositiveIntegerField(blank=True, help_text='Required for TCP targets', null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='address',
            field=models.CharField(help_text='Hostname, IP address, or URL (for HTTP targets)', max_length=255),
        ),
    ]
