"""
Report generation utilities for ISP Accountability Monitor.
Currently generates HTML reports that can be printed to PDF.
Future: Add PDF library integration (weasyprint, reportlab, or wkhtmltopdf).
"""
from datetime import datetime, timezone


def generate_report_html(
    period_start: str,
    period_end: str,
    outages: list[dict],
    summary: dict = None,
) -> str:
    """Generate HTML report for printing to PDF."""

    template = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ISP Accountability Report</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
        }
        .header {
            background: #1a1a2e;
            color: white;
            padding: 20px;
            text-align: center;
        }
        .header h1 {
            margin: 0;
            font-size: 1.8rem;
        }
        .meta {
            background: #f5f5f5;
            padding: 10px;
            border-bottom: 2px solid #4fc3f7;
            font-family: monospace;
            font-size: 0.9rem;
        }
        .section {
            margin-top: 20px;
            background: white;
            border: 1px solid #ddd;
            border-radius: 8px;
            padding: 15px;
        }
        .section h2 {
            color: #4fc3f7;
            margin-top: 0;
            border-bottom: 1px solid #eee;
            padding-bottom: 10px;
        }
        .metric-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 10px;
        }
        .metric {
            background: #f5f5f5;
            padding: 10px;
            border-radius: 4px;
            text-align: center;
        }
        .metric-label {
            color: #666;
            font-size: 0.85rem;
        }
        .metric-value {
            font-size: 1.3rem;
            font-weight: bold;
            color: #333;
        }
        .outage-table {
            width: 100%;
            border-collapse: collapse;
            font-size: 0.9rem;
        }
        .outage-table th,
        .outage-table td {
            padding: 8px;
            text-align: left;
            border-bottom: 1px solid #eee;
        }
        .outage-table th {
            background: #f5f5f5;
            font-weight: 600;
        }
        .severity-critical { color: #d32f2f; }
        .severity-severe { color: #f57c00; }
        .severity-moderate { color: #f9a825; }
        .severity-minor { color: #388e3c; }
        .notes {
            font-style: italic;
            color: #666;
            font-size: 0.85rem;
        }
        .footer {
            margin-top: 20px;
            text-align: center;
            font-size: 0.8rem;
            color: #999;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>ISP Connectivity Evidence Report</h1>
        <p style="margin-top: 5px;">Generated by ISP Accountability Monitor</p>
    </div>

    <div class="meta">
        <strong>Period:</strong> {period_start} to {period_end}<br>
        <strong>Report Generated:</strong> {generated}<br>
        <strong>Total Outages:</strong> {outage_count}<br>
        <strong>Total Duration:</strong> {total_duration}
    </div>

    <div class="section">
        <h2>Executive Summary</h2>
        <p>This report documents network connectivity incidents detected during the monitoring period. Each incident has been classified based on evidence analysis to determine whether it represents a local device issue, upstream/property network failure, or endpoint-specific problem.</p>

        {summary}

        <div class="notes">
            <strong>Note:</strong> This report is generated automatically. The tool does not provide legal conclusions about SLA breaches - only evidence-based technical analysis. Contractual SLA qualification requires review of the actual service agreement and applicable exclusions.
        </div>
    </div>

    {outages_section}

    <div class="footer">
        ISP Accountability Monitor v1.0<br>
        Local-first network monitoring tool with no cloud dependency
    </div>
</body>
</html>"""

    # Build summary HTML
    summary_html = ""
    if summary:
        uptime_target = summary.get("uptime_target", "99.99%")
        observed_availability = summary.get("observed_availability", "N/A%")
        downtime_budget = summary.get("downtime_budget_minutes", 0)
        remaining_budget = summary.get("remaining_budget_minutes", 0)

        summary_html = f"""
        <div class="metric-grid">
            <div class="metric">
                <div class="metric-label">SLA Target</div>
                <div class="metric-value">{uptime_target}</div>
            </div>
            <div class="metric">
                <div class="metric-label">Observed Availability</div>
                <div class="metric-value">{observed_availability}</div>
            </div>
            <div class="metric">
                <div class="metric-label">Downtime Budget</div>
                <div class="metric-value">{downtime_budget} min</div>
            </div>
            <div class="metric">
                <div class="metric-label">Remaining Budget</div>
                <div class="metric-value">{remaining_budget} min</div>
            </div>
        </div>
        """

    # Build outages section HTML
    if not outages:
        outages_section = """<div class="section"><h2>Detailed Incident Log</h2><p>No outages detected during this monitoring period.</p></div>"""
    else:
        outage_rows = ""
        for outage in outages[-10:]:  # Last 10 outages
            start_time = datetime.fromisoformat(outage["start_timestamp_utc"].replace("Z", "+00:00")).strftime("%Y-%m-%d %H:%M")
            duration = outage.get("duration_seconds", 0)
            severity_class = f"severity-{outage.get('severity', 'minor') or 'minor'}"

            outage_rows += f"""<tr>
                <td>{start_time}</td>
                <td class="{severity_class}">{duration}s</td>
                <td>{outage.get('targets_affected', 0)}</td>
                <td style="max-width: 200px; font-size: 0.85rem;">{outage.get('classification_reason', '')[:100]}...</td>
            </tr>"""

        outages_section = f"""<div class="section"><h2>Detailed Incident Log</h2><table class="outage-table"><thead><tr>
                <th>Start Time</th><th>Duration</th><th>Targets Affected</th><th>Evidence Reasoning</th>
            </tr></thead><tbody>{outage_rows}</tbody></table></div>"""

    return template.format(
        period_start=period_start,
        period_end=period_end,
        generated=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC"),
        outage_count=len(outages),
        total_duration=f"{summary.get('total_duration_seconds', 0):.1f}s" if summary else "N/A",
        summary=summary_html,
        outages_section=outages_section,
    )
