# Generated by Django 6.1.1 on 2026-09-20 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(help_text='Matches an SLAMetric key, e.g. "latency_ms"', max_length=30)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, default='', max_length=20)),
                ('population_context', models.CharField(blank=True, default='', max_length=255)),
                ('technology_type', models.CharField(blank=True, default='', help_text='e.g. "cable", "fiber", "DSL"', max_length=100)),
                ('geographic_scope', models.CharField(blank=True, default='', max_length=100)),
                ('source', models.CharField(max_length=255)),
                ('source_url', models.URLField(blank=True, default='')),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('methodology', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['metric', '-version'],
                'unique_together': {('metric', 'version', 'technology_type', 'geographic_scope')},
            },
        ),
    ]
