# Generated by Django 6.1.1 on 2026-09-20 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_seed_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICMPMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('address_family', models.CharField(choices=[('ipv4', 'IPv4'), ('ipv6', 'IPv6')], max_length=4)),
                ('sent', models.PositiveIntegerField()),
                ('received', models.PositiveIntegerField()),
                ('loss_pct', models.FloatField()),
                ('min_rtt_ms', models.FloatField(blank=True, null=True)),
                ('avg_rtt_ms', models.FloatField(blank=True, null=True)),
                ('median_rtt_ms', models.FloatField(blank=True, null=True)),
                ('max_rtt_ms', models.FloatField(blank=True, null=True)),
                ('p95_rtt_ms', models.FloatField(blank=True, null=True)),
                ('p99_rtt_ms', models.FloatField(blank=True, null=True)),
                ('jitter_ms', models.FloatField(blank=True, null=True)),
                ('error', models.CharField(blank=True, default='', max_length=255)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icmp_measurements', to='core.target')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['target', 'timestamp'], name='measurement_target__6cb23d_idx')],
            },
        ),
    ]
