# Generated by Django 6.1.1 on 2026-09-20 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ondemandtestrequest_target_port_alter_target_address'),
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BufferbloatTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('baseline_rtt_ms', models.FloatField()),
                ('loaded_rtt_download_ms', models.FloatField(blank=True, null=True)),
                ('loaded_rtt_upload_ms', models.FloatField(blank=True, null=True)),
                ('loaded_rtt_bidirectional_ms', models.FloatField(blank=True, null=True)),
                ('loss_during_load_pct', models.FloatField(blank=True, null=True)),
                ('throughput_during_load_mbps', models.FloatField(blank=True, null=True)),
                ('recovery_time_s', models.FloatField(blank=True, null=True)),
                ('classification', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='InterfaceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('interface_name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=20)),
                ('link_speed_mbps', models.IntegerField(blank=True, null=True)),
                ('bytes_sent', models.BigIntegerField()),
                ('bytes_received', models.BigIntegerField()),
                ('packets_sent', models.BigIntegerField()),
                ('packets_received', models.BigIntegerField()),
                ('errors_in', models.PositiveIntegerField()),
                ('errors_out', models.PositiveIntegerField()),
                ('discards', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['interface_name', 'timestamp'], name='measurement_interfa_c0ba49_idx')],
            },
        ),
        migrations.CreateModel(
            name='RouteChangeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('previous_route_hash', models.CharField(blank=True, default='', max_length=255)),
                ('new_route_hash', models.CharField(max_length=255)),
                ('hop_count_before', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hop_count_after', models.PositiveSmallIntegerField()),
                ('first_hop_changed', models.BooleanField()),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_change_events', to='core.target')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RouteTestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('address_family', models.CharField(choices=[('ipv4', 'IPv4'), ('ipv6', 'IPv6')], max_length=4)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_test_runs', to='core.target')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RouteHop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hop_number', models.PositiveSmallIntegerField()),
                ('ip_address', models.CharField(blank=True, default='', max_length=255)),
                ('hostname', models.CharField(blank=True, default='', max_length=255)),
                ('rtt_ms', models.FloatField(blank=True, null=True)),
                ('timeout', models.BooleanField(default=False)),
                ('route_test_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hops', to='measurements.routetestrun')),
            ],
            options={
                'ordering': ['route_test_run', 'hop_number'],
            },
        ),
        migrations.CreateModel(
            name='TCPMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('port', models.PositiveIntegerField()),
                ('success', models.BooleanField()),
                ('error_type', models.CharField(blank=True, default='', max_length=50)),
                ('connect_time_ms', models.FloatField(blank=True, null=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tcp_measurements', to='core.target')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ThroughputMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('test_type', models.CharField(choices=[('download', 'Download only'), ('upload', 'Upload only'), ('bidirectional', 'Download + Upload')], max_length=15)),
                ('mbps_down', models.FloatField(blank=True, null=True)),
                ('mbps_up', models.FloatField(blank=True, null=True)),
                ('avg_mbps', models.FloatField(blank=True, null=True)),
                ('peak_mbps', models.FloatField(blank=True, null=True)),
                ('min_mbps', models.FloatField(blank=True, null=True)),
                ('variance', models.FloatField(blank=True, null=True)),
                ('duration_s', models.FloatField(blank=True, null=True)),
                ('endpoint', models.CharField(blank=True, default='', max_length=255)),
                ('address_family', models.CharField(choices=[('ipv4', 'IPv4'), ('ipv6', 'IPv6')], default='ipv4', max_length=4)),
                ('test_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('error', models.CharField(blank=True, default='', max_length=255)),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='throughput_measurements', to='core.target')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DNSMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('resolver', models.CharField(help_text='Resolver address used, e.g. 1.1.1.1', max_length=255)),
                ('query_name', models.CharField(max_length=255)),
                ('query_type', models.CharField(default='A', max_length=10)),
                ('resolution_time_ms', models.FloatField(blank=True, null=True)),
                ('result_type', models.CharField(choices=[('success', 'Success'), ('timeout', 'Timeout'), ('servfail', 'SERVFAIL'), ('nxdomain', 'NXDOMAIN'), ('error', 'Other error')], max_length=10)),
                ('resolved_ip', models.CharField(blank=True, default='', max_length=255)),
                ('address_family', models.CharField(choices=[('ipv4', 'IPv4'), ('ipv6', 'IPv6')], max_length=4)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dns_measurements', to='core.target')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['target', 'timestamp'], name='measurement_target__1b4a90_idx')],
            },
        ),
        migrations.CreateModel(
            name='HTTPMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('dns_time_ms', models.FloatField(blank=True, null=True)),
                ('connect_time_ms', models.FloatField(blank=True, null=True)),
                ('tls_time_ms', models.FloatField(blank=True, null=True)),
                ('ttfb_ms', models.FloatField(blank=True, null=True)),
                ('total_time_ms', models.FloatField(blank=True, null=True)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('redirect_count', models.PositiveSmallIntegerField(default=0)),
                ('address_family', models.CharField(choices=[('ipv4', 'IPv4'), ('ipv6', 'IPv6')], max_length=4)),
                ('error_type', models.CharField(blank=True, default='', max_length=50)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='http_measurements', to='core.target')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['target', 'timestamp'], name='measurement_target__cfe652_idx')],
            },
        ),
        migrations.CreateModel(
            name='MTUTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('largest_successful_size', models.PositiveIntegerField(help_text='Bytes, ICMP payload size')),
                ('df_behavior', models.CharField(help_text='e.g. "honored", "fragmented", "unknown"', max_length=50)),
                ('pmtud_response', models.CharField(blank=True, default='', max_length=100)),
                ('failure_threshold', models.PositiveIntegerField(help_text='Smallest size that failed, bytes')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mtu_test_results', to='core.target')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['target', 'timestamp'], name='measurement_target__6c52a4_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='routetestrun',
            index=models.Index(fields=['target', 'timestamp'], name='measurement_target__6ccfd4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='routehop',
            unique_together={('route_test_run', 'hop_number')},
        ),
        migrations.AddIndex(
            model_name='tcpmeasurement',
            index=models.Index(fields=['target', 'timestamp'], name='measurement_target__67010c_idx'),
        ),
    ]
