# Generated by Django 6.1.1 on 2026-09-20 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ondemandtestrequest_target_port_alter_target_address'),
        ('measurements', '0002_bufferbloattest_interfacemetric_routechangeevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=30)),
                ('period_start', models.DateField()),
                ('avg_value', models.FloatField()),
                ('min_value', models.FloatField()),
                ('max_value', models.FloatField()),
                ('p95_value', models.FloatField()),
                ('sample_count', models.PositiveIntegerField()),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_aggregates', to='core.target')),
            ],
            options={
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['metric', 'period_start'], name='measurement_metric_b64037_idx')],
                'unique_together': {('target', 'metric', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='HourlyAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=30)),
                ('period_start', models.DateTimeField()),
                ('avg_value', models.FloatField()),
                ('min_value', models.FloatField()),
                ('max_value', models.FloatField()),
                ('p95_value', models.FloatField()),
                ('sample_count', models.PositiveIntegerField()),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hourly_aggregates', to='core.target')),
            ],
            options={
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['metric', 'period_start'], name='measurement_metric_fff95f_idx')],
                'unique_together': {('target', 'metric', 'period_start')},
            },
        ),
    ]
