# Generated by Django 6.1.1 on 2026-09-20 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('outage', 'Outage'), ('periodic', 'Periodic'), ('custom', 'Custom')], max_length=20)),
                ('format', models.CharField(choices=[('html', 'HTML'), ('pdf', 'PDF'), ('csv', 'CSV'), ('json', 'JSON')], max_length=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.CharField(blank=True, default='', max_length=500)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='incidents.incident')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
