# Generated by Django 6.1.1 on 2026-09-20 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('outage', 'Outage'), ('micro_outage', 'Micro-outage'), ('packet_loss', 'Packet loss'), ('latency_degradation', 'Latency degradation'), ('jitter_degradation', 'Jitter degradation'), ('throughput_degradation', 'Throughput degradation'), ('dns_failure', 'DNS failure'), ('dns_degradation', 'DNS degradation'), ('route_change', 'Route change'), ('ipv6_failure', 'IPv6 failure'), ('mtu_failure', 'MTU failure'), ('bufferbloat', 'Bufferbloat'), ('connection_failure', 'Connection failure')], max_length=30)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=10)),
                ('affected_tests', models.JSONField(blank=True, default=list)),
                ('affected_destinations', models.JSONField(blank=True, default=list)),
                ('recovery_status', models.CharField(choices=[('ongoing', 'Ongoing'), ('recovered', 'Recovered'), ('unknown', 'Unknown')], default='ongoing', max_length=10)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('outage', 'Outage'), ('micro_outage', 'Micro-outage'), ('packet_loss', 'Packet loss'), ('latency_degradation', 'Latency degradation'), ('jitter_degradation', 'Jitter degradation'), ('throughput_degradation', 'Throughput degradation'), ('dns_failure', 'DNS failure'), ('dns_degradation', 'DNS degradation'), ('route_change', 'Route change'), ('ipv6_failure', 'IPv6 failure'), ('mtu_failure', 'MTU failure'), ('bufferbloat', 'Bufferbloat'), ('connection_failure', 'Connection failure')], max_length=30)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=10)),
                ('description', models.TextField()),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='incidents.incident')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='EventEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_type', models.CharField(help_text='Measurement model name, e.g. "ICMPMeasurement"', max_length=30)),
                ('measurement_id', models.PositiveIntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='incidents.event')),
            ],
            options={
                'indexes': [models.Index(fields=['measurement_type', 'measurement_id'], name='incidents_e_measure_e1bd4b_idx')],
            },
        ),
    ]
