# Generated by Django 6.1.1 on 2026-09-20 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkStateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('previous_state', models.CharField(choices=[('online', 'Online'), ('degraded', 'Degraded'), ('offline', 'Offline'), ('recovering', 'Recovering')], max_length=10)),
                ('new_state', models.CharField(choices=[('online', 'Online'), ('degraded', 'Degraded'), ('offline', 'Offline'), ('recovering', 'Recovering')], max_length=10)),
                ('reason', models.CharField(max_length=255)),
                ('confirming_targets', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StateMachineConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutive_failures_for_degraded', models.PositiveIntegerField(default=2, help_text='Consecutive failed probes on a target before it counts as "failing"')),
                ('consecutive_failures_for_offline', models.PositiveIntegerField(default=4, help_text='Consecutive failed probes on a target before it counts as "severely failing"')),
                ('min_independent_targets_failing', models.PositiveIntegerField(default=2, help_text='Number of independent targets that must agree before a transition is confirmed')),
                ('recovery_confirmation_successes', models.PositiveIntegerField(default=3, help_text='Consecutive successful probes required to confirm full recovery')),
                ('micro_outage_threshold_seconds', models.PositiveIntegerField(default=60, help_text='Outages shorter than this are classified MICRO_OUTAGE instead of OUTAGE')),
            ],
            options={
                'verbose_name': 'State machine configuration',
                'verbose_name_plural': 'State machine configuration',
            },
        ),
    ]
